### ISSUE TITLE
为啥好多相互冲突的定义

### ISSUE THREAD

**Issue by qingshanbugai** [Tencent/weui-wxss#45]
.weui-footer__link:before {
  content: " ";
  position: absolute;
  left: 0;
 #  top: 0;
  width: 1px;
 #  bottom: 0;
  border-left: 1rpx solid #c7c7c7;
  color: #c7c7c7;
  left: -.65em;
  # top: 0.36em;
  # bottom: 0.36em;
}

有好多类似这样的前后定义冲突的，我是从./dist/weui文件夹下直接拖进项目的，不是很理解为啥会这样

**Comment by ziliwesley** [comment]
在未知其上一层容器的高度时, 这样的写法可以实现对高度的自动计算

比如:

```html
<div class="block-outer">
  <div class="block-inner"></div>
</div>
```


```css
.block-outer {
  /** 确保 .block-inner 是相对于此级元素绝对定位 **/
  position: relative;
  background-color: #eee;
  width: 100px;
  height: 80px;
}

.block-inner {
  position: absolute;
  background-color: rgba(0, 0, 0, .8);
  top: 10px;
  left: 10px;
  right: 10px;
  bottom: 10px;
}
```

`.block-inner` 的实际宽高则为 80 x 60.
